services:
  - type: web
    name: mxplayer-downloader
    env: node
    buildCommand: |
      # Update package list and install required dependencies
      apt-get update
      apt-get install -y python3 python3-pip wget

      # Install yt-dlp using pip and make it executable
      python3 -m pip install --upgrade pip
      python3 -m pip install --upgrade yt-dlp

      # Create symlink to make yt-dlp accessible globally
      ln -sf /usr/local/bin/yt-dlp /usr/bin/yt-dlp
      
      # Verify installation
      yt-dlp --version
      
      # Install Node dependencies
      npm install
    startCommand: node server.js
    envVars:
      - key: zeondivine@gmail.com
        sync: false
      - key: Sassy@123
        sync: false
      - key: PORT
        value: 3000
      - key: PATH
        value: /usr/local/bin:/usr/bin:${PATH}
    plan: starter
    healthCheckPath: /status
    autoDeploy: true
